Illuminate\Contracts\Container\BindingResolutionException: Target class [App\Modules\Courses\StudentsCoursesEnrollmentsValidator]
does not exist. in file /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 877

#0 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\Container\Container->build('App\\Modules\\Cou...')
#1 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(855): Illuminate\Container\Container->resolve('App\\Modules\\Cou...', Array, true)
#2 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve('App\\Modules\\Cou...', Array)
#3 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(840): Illuminate\Container\Container->make('App\\Modules\\Cou...', Array)
#4 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(1025): Illuminate\Foundation\Application->make('App\\Modules\\Cou...')
#5 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(945): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#6 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(906): Illuminate\Container\Container->resolveDependencies(Array)
#7 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\Container\Container->build('App\\Modules\\Cou...')
#8 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(855): Illuminate\Container\Container->resolve('App\\Modules\\Cou...', Array, true)
#9 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve('App\\Modules\\Cou...', Array)
#10 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(840): Illuminate\Container\Container->make('App\\Modules\\Cou...', Array)
#11 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(1025): Illuminate\Foundation\Application->make('App\\Modules\\Cou...')
#12 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(945): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#13 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(906): Illuminate\Container\Container->resolveDependencies(Array)
#14 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\Container\Container->build('App\\Modules\\Stu...')
#15 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(855): Illuminate\Container\Container->resolve('App\\Modules\\Stu...', Array, true)
#16 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve('App\\Modules\\Stu...', Array)
#17 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(840): Illuminate\Container\Container->make('App\\Modules\\Stu...', Array)
#18 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(1025): Illuminate\Foundation\Application->make('App\\Modules\\Stu...')
#19 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(945): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#20 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(906): Illuminate\Container\Container->resolveDependencies(Array)
#21 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\Container\Container->build('App\\Modules\\Stu...')
#22 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(855): Illuminate\Container\Container->resolve('App\\Modules\\Stu...', Array, true)
#23 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve('App\\Modules\\Stu...', Array)
#24 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(840): Illuminate\Container\Container->make('App\\Modules\\Stu...', Array)
#25 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(1025): Illuminate\Foundation\Application->make('App\\Modules\\Stu...')
#26 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(945): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#27 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(906): Illuminate\Container\Container->resolveDependencies(Array)
#28 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\Container\Container->build('App\\Modules\\Stu...')
#29 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(855): Illuminate\Container\Container->resolve('App\\Modules\\Stu...', Array, true)
#30 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve('App\\Modules\\Stu...', Array)
#31 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(840): Illuminate\Container\Container->make('App\\Modules\\Stu...', Array)
#32 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(1025): Illuminate\Foundation\Application->make('App\\Modules\\Stu...')
#33 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(945): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#34 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(906): Illuminate\Container\Container->resolveDependencies(Array)
#35 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\Container\Container->build('App\\Http\\Contro...')
#36 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(855): Illuminate\Container\Container->resolve('App\\Http\\Contro...', Array, true)
#37 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve('App\\Http\\Contro...', Array)
#38 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(840): Illuminate\Container\Container->make('App\\Http\\Contro...', Array)
#39 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Routing/Route.php(275): Illuminate\Foundation\Application->make('App\\Http\\Contro...')
#40 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Routing/Route.php(1081): Illuminate\Routing\Route->getController()
#41 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Routing/Route.php(1024): Illuminate\Routing\Route->controllerMiddleware()
#42 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\Routing\Route->gatherMiddleware()
#43 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Routing/Router.php(719): Illuminate\Routing\Router->gatherRouteMiddleware(Object(Illuminate\Routing\Route))
#44 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#45 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#46 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#47 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#48 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#49 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#65 /Users/developer/Documents/code/api-student/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#66 /Users/developer/Documents/code/api-student/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#67 /Users/developer/.composer/vendor/laravel/valet/server.php(234): require('/Users/develope...')
#68 {main}
